SELECT 
    f.FACULTY_NAME AS [Факультет],
    p.PROFESSION_NAME AS [Специальность],
    s.SUBJECT_NAME AS [Дисциплина],
    ROUND(AVG(CAST(pr.NOTE AS FLOAT)), 2) AS [Средняя оценка]
FROM dbo.FACULTY f
INNER JOIN dbo.[GROUP] g ON f.FACULTY = g.FACULTY
INNER JOIN dbo.PROFESSION p ON g.PROFESSION = p.PROFESSION
INNER JOIN dbo.STUDENT st ON g.IDGROUP = st.IDGROUP
INNER JOIN dbo.PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
INNER JOIN dbo.SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE f.FACULTY = 'ТОВ'
GROUP BY ROLLUP (f.FACULTY_NAME, p.PROFESSION_NAME, s.SUBJECT_NAME);
SELECT 
    f.FACULTY_NAME AS [Факультет],
    p.PROFESSION_NAME AS [Специальность],
    s.SUBJECT_NAME AS [Дисциплина],
    ROUND(AVG(CAST(pr.NOTE AS FLOAT)), 2) AS [Средняя оценка]
FROM dbo.FACULTY f
INNER JOIN dbo.[GROUP] g ON f.FACULTY = g.FACULTY
INNER JOIN dbo.PROFESSION p ON g.PROFESSION = p.PROFESSION
INNER JOIN dbo.STUDENT st ON g.IDGROUP = st.IDGROUP
INNER JOIN dbo.PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
INNER JOIN dbo.SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE f.FACULTY = 'ТОВ'
GROUP BY CUBE (f.FACULTY_NAME, p.PROFESSION_NAME, s.SUBJECT_NAME);
SELECT 
    p.PROFESSION_NAME AS [Специальность],
    s.SUBJECT_NAME AS [Дисциплина],
    ROUND(AVG(CAST(pr.NOTE AS FLOAT)), 2) AS [Средняя оценка]
FROM dbo.FACULTY f
INNER JOIN dbo.[GROUP] g ON f.FACULTY = g.FACULTY
INNER JOIN dbo.PROFESSION p ON g.PROFESSION = p.PROFESSION
INNER JOIN dbo.STUDENT st ON g.IDGROUP = st.IDGROUP
INNER JOIN dbo.PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
INNER JOIN dbo.SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE f.FACULTY = 'ТОВ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME

UNION

SELECT 
    p.PROFESSION_NAME AS [Специальность],
    s.SUBJECT_NAME AS [Дисциплина],
    ROUND(AVG(CAST(pr.NOTE AS FLOAT)), 2) AS [Средняя оценка]
FROM dbo.FACULTY f
INNER JOIN dbo.[GROUP] g ON f.FACULTY = g.FACULTY
INNER JOIN dbo.PROFESSION p ON g.PROFESSION = p.PROFESSION
INNER JOIN dbo.STUDENT st ON g.IDGROUP = st.IDGROUP
INNER JOIN dbo.PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
INNER JOIN dbo.SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE f.FACULTY = 'ХТиТ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME;

SELECT 
    p.PROFESSION_NAME AS [Специальность],
    s.SUBJECT_NAME AS [Дисциплина],
    ROUND(AVG(CAST(pr.NOTE AS FLOAT)), 2) AS [Средняя оценка]
FROM dbo.FACULTY f
INNER JOIN dbo.[GROUP] g ON f.FACULTY = g.FACULTY
INNER JOIN dbo.PROFESSION p ON g.PROFESSION = p.PROFESSION
INNER JOIN dbo.STUDENT st ON g.IDGROUP = st.IDGROUP
INNER JOIN dbo.PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
INNER JOIN dbo.SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE f.FACULTY = 'ТОВ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME

UNION ALL

SELECT 
    p.PROFESSION_NAME AS [Специальность],
    s.SUBJECT_NAME AS [Дисциплина],
    ROUND(AVG(CAST(pr.NOTE AS FLOAT)), 2) AS [Средняя оценка]
FROM dbo.FACULTY f
INNER JOIN dbo.[GROUP] g ON f.FACULTY = g.FACULTY
INNER JOIN dbo.PROFESSION p ON g.PROFESSION = p.PROFESSION
INNER JOIN dbo.STUDENT st ON g.IDGROUP = st.IDGROUP
INNER JOIN dbo.PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
INNER JOIN dbo.SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE f.FACULTY = 'ХТиТ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME;

SELECT 
    p.PROFESSION_NAME AS [Специальность],
    s.SUBJECT_NAME AS [Дисциплина],
    ROUND(AVG(CAST(pr.NOTE AS FLOAT)), 2) AS [Средняя оценка]
FROM dbo.FACULTY f
INNER JOIN dbo.[GROUP] g ON f.FACULTY = g.FACULTY
INNER JOIN dbo.PROFESSION p ON g.PROFESSION = p.PROFESSION
INNER JOIN dbo.STUDENT st ON g.IDGROUP = st.IDGROUP
INNER JOIN dbo.PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
INNER JOIN dbo.SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE f.FACULTY = 'ТОВ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME

INTERSECT

SELECT 
    p.PROFESSION_NAME AS [Специальность],
    s.SUBJECT_NAME AS [Дисциплина],
    ROUND(AVG(CAST(pr.NOTE AS FLOAT)), 2) AS [Средняя оценка]
FROM dbo.FACULTY f
INNER JOIN dbo.[GROUP] g ON f.FACULTY = g.FACULTY
INNER JOIN dbo.PROFESSION p ON g.PROFESSION = p.PROFESSION
INNER JOIN dbo.STUDENT st ON g.IDGROUP = st.IDGROUP
INNER JOIN dbo.PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
INNER JOIN dbo.SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE f.FACULTY = 'ХТиТ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME;

SELECT 
    p.PROFESSION_NAME AS [Специальность],
    s.SUBJECT_NAME AS [Дисциплина],
    ROUND(AVG(CAST(pr.NOTE AS FLOAT)), 2) AS [Средняя оценка]
FROM dbo.FACULTY f
INNER JOIN dbo.[GROUP] g ON f.FACULTY = g.FACULTY
INNER JOIN dbo.PROFESSION p ON g.PROFESSION = p.PROFESSION
INNER JOIN dbo.STUDENT st ON g.IDGROUP = st.IDGROUP
INNER JOIN dbo.PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
INNER JOIN dbo.SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE f.FACULTY = 'ТОВ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME

EXCEPT

SELECT 
    p.PROFESSION_NAME AS [Специальность],
    s.SUBJECT_NAME AS [Дисциплина],
    ROUND(AVG(CAST(pr.NOTE AS FLOAT)), 2) AS [Средняя оценка]
FROM dbo.FACULTY f
INNER JOIN dbo.[GROUP] g ON f.FACULTY = g.FACULTY
INNER JOIN dbo.PROFESSION p ON g.PROFESSION = p.PROFESSION
INNER JOIN dbo.STUDENT st ON g.IDGROUP = st.IDGROUP
INNER JOIN dbo.PROGRESS pr ON st.IDSTUDENT = pr.IDSTUDENT
INNER JOIN dbo.SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE f.FACULTY = 'ХТиТ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME;
