USE UNIVER;
GO

SELECT 
    p.PULPIT_NAME AS PulpitName
FROM dbo.PULPIT p
WHERE p.FACULTY IN (
    SELECT pr.FACULTY
    FROM dbo.PROFESSION pr
    WHERE pr.PROFESSION_NAME LIKE N'%технологи[я|и]%'
);
GO

SELECT DISTINCT 
    p.PULPIT_NAME AS PulpitName
FROM dbo.PULPIT p
INNER JOIN (
    SELECT pr.FACULTY
    FROM dbo.PROFESSION pr
    WHERE pr.PROFESSION_NAME LIKE N'%технологи[я|и]%'
) pr ON p.FACULTY = pr.FACULTY;
GO

SELECT DISTINCT 
    p.PULPIT_NAME AS PulpitName
FROM dbo.PULPIT p
INNER JOIN dbo.FACULTY f ON p.FACULTY = f.FACULTY
INNER JOIN dbo.PROFESSION pr ON f.FACULTY = pr.FACULTY
WHERE pr.PROFESSION_NAME LIKE N'%технологи[я|и]%';
GO

SELECT 
    a.AUDITORIUM,
    a.AUDITORIUM_NAME,
    a.AUDITORIUM_TYPE,
    a.AUDITORIUM_CAPACITY
FROM dbo.AUDITORIUM a
WHERE a.AUDITORIUM_CAPACITY = (
    SELECT TOP 1 a2.AUDITORIUM_CAPACITY
    FROM dbo.AUDITORIUM a2
    WHERE a2.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE
    ORDER BY a2.AUDITORIUM_CAPACITY DESC
)
ORDER BY a.AUDITORIUM_CAPACITY DESC;
GO

SELECT 
    f.FACULTY_NAME
FROM dbo.FACULTY f
WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.PULPIT p
    WHERE p.FACULTY = f.FACULTY
);
GO

SELECT 
    (SELECT AVG(CAST(prg.NOTE AS FLOAT)) FROM dbo.PROGRESS prg WHERE prg.SUBJECT = 'ПЗ') AS AvgNote_PZ,
    (SELECT AVG(CAST(prg.NOTE AS FLOAT)) FROM dbo.PROGRESS prg WHERE prg.SUBJECT = 'СУБД') AS AvgNote_SUBD
FROM (SELECT 1 AS Dummy) AS d; 
GO

SELECT 
    s.IDSTUDENT,
    s.[NAME]
FROM dbo.STUDENT s
INNER JOIN dbo.PROGRESS p ON s.IDSTUDENT = p.IDSTUDENT
GROUP BY s.IDSTUDENT, s.[NAME]
HAVING MIN(p.NOTE) >= ALL (
    SELECT MIN(prg.NOTE)
    FROM dbo.PROGRESS prg
    WHERE prg.SUBJECT = 'СУБД'
);
GO

SELECT DISTINCT 
    s.IDSTUDENT,
    s.[NAME]
FROM dbo.STUDENT s
INNER JOIN dbo.PROGRESS p ON s.IDSTUDENT = p.IDSTUDENT
WHERE p.NOTE > ANY (
    SELECT prg.NOTE
    FROM dbo.PROGRESS prg
    WHERE prg.SUBJECT = 'ПЗ'
);
GO